import type { CheckStatus, Concept, Effort, Priority, RiskRating } from "./types";

/**
 * Deterministic remediation knowledge base. The same control ID always
 * produces the same title/explanation/recommendation — no AI-generated
 * text per scan, per the build brief's explicit instruction ("the same
 * input should generally produce the same recommendation"). This makes
 * the tool's output consistent, testable, and reviewable in one file.
 */

export interface KnowledgeBaseEntry {
  controlId: string;
  concept: Concept;
  title: string;
  why: string;
  recommendation: string;
  riskRating: RiskRating;
  priority: Priority;
  effort: Effort;
  status: CheckStatus;
}

export const KNOWLEDGE_BASE: Record<string, KnowledgeBaseEntry> = {
  SPF_MISSING: {
    controlId: "SPF_MISSING",
    concept: "spf",
    title: "No SPF record was found",
    why: "SPF lets receiving mail systems check whether a message claiming to be from your domain actually came from a server you've authorised. Without it, there's no published list for anyone to check against.",
    recommendation: "Identify every system that legitimately sends email for your domain (your mailbox provider, and any marketing, invoicing, or booking tools that send on your behalf), then publish an SPF record listing them.",
    riskRating: "high",
    priority: "now",
    effort: "low",
    status: "high-priority",
  },
  SPF_PASS_ALL: {
    controlId: "SPF_PASS_ALL",
    concept: "spf",
    title: "Your SPF record permits any server to send mail for your domain",
    why: "An SPF record ending in \"+all\" tells receiving systems to accept mail from any source as if it came from you, which defeats the purpose of having SPF at all.",
    recommendation: "Replace the permissive \"+all\" ending with a restrictive one, after confirming every legitimate sending source is already listed.",
    riskRating: "high",
    priority: "now",
    effort: "very-low",
    status: "high-priority",
  },
  SPF_SOFT_OR_NEUTRAL: {
    controlId: "SPF_SOFT_OR_NEUTRAL",
    concept: "spf",
    title: "SPF is present but does not clearly reject unauthorised senders",
    why: "SPF is published but its ending mechanism suggests suspicious mail may still receive a less decisive treatment, rather than being clearly flagged.",
    recommendation: "Before moving to a stricter policy, confirm all legitimate mail services are correctly listed, then move toward an ending that clearly fails unauthorised senders.",
    riskRating: "moderate",
    priority: "next",
    effort: "low",
    status: "attention",
  },
  SPF_MALFORMED: {
    controlId: "SPF_MALFORMED",
    concept: "spf",
    title: "SPF configuration could not be reliably interpreted",
    why: "Either more than one SPF record was published for this domain, or the record doesn't follow the expected format. Multiple or malformed SPF records can cause mail systems to fail authentication checks unpredictably, sometimes for legitimate mail.",
    recommendation: "Consolidate to a single, correctly formatted SPF record.",
    riskRating: "moderate",
    priority: "now",
    effort: "low",
    status: "attention",
  },
  SPF_LOOKUP_LIMIT_EXCEEDED: {
    controlId: "SPF_LOOKUP_LIMIT_EXCEEDED",
    concept: "spf",
    title: "SPF record may exceed the DNS lookup limit",
    why: "SPF allows at most 10 DNS lookups during evaluation. A record that exceeds this can fail unpredictably (a \"permanent error\"), sometimes causing legitimate mail to fail authentication.",
    recommendation: "Review the includes and mechanisms in your SPF record with your mail/IT provider and simplify where possible.",
    riskRating: "moderate",
    priority: "next",
    effort: "moderate",
    status: "attention",
  },
  SPF_GOOD: {
    controlId: "SPF_GOOD",
    concept: "spf",
    title: "SPF is configured with a clear enforcement policy",
    why: "Your domain publishes an SPF policy that clearly restricts which mail systems are permitted to send email for it.",
    recommendation: "No action needed. Revisit if you add or remove a mail-sending service.",
    riskRating: "informational",
    priority: "monitor",
    effort: "very-low",
    status: "good",
  },

  DMARC_MISSING: {
    controlId: "DMARC_MISSING",
    concept: "dmarc",
    title: "No DMARC record was found",
    why: "DMARC helps receiving mail systems determine how to handle messages that fail SPF or DKIM checks, and gives you visibility into who is sending mail using your domain.",
    recommendation: "Begin by identifying every legitimate system that sends mail for your domain. Confirm SPF and DKIM are correctly configured, then introduce a DMARC record in monitoring mode (p=none with a reporting address) before moving toward enforcement.",
    riskRating: "high",
    priority: "now",
    effort: "low",
    status: "high-priority",
  },
  DMARC_MONITORING_ONLY: {
    controlId: "DMARC_MONITORING_ONLY",
    concept: "dmarc",
    title: "DMARC is present but set to monitoring only",
    why: "A DMARC policy of \"p=none\" means reports are generated, but receiving mail systems are not instructed to do anything about messages that fail authentication.",
    recommendation: "Once SPF and DKIM are confirmed correctly configured for all legitimate senders, move DMARC toward an enforcement policy (quarantine, then reject) in stages.",
    riskRating: "moderate",
    priority: "next",
    effort: "moderate",
    status: "attention",
  },
  DMARC_MALFORMED: {
    controlId: "DMARC_MALFORMED",
    concept: "dmarc",
    title: "DMARC configuration could not be reliably interpreted",
    why: "The DMARC record found doesn't follow the expected format, or more than one was published, which can cause receiving mail systems to ignore it entirely.",
    recommendation: "Correct the DMARC record with your mail/IT provider so there is exactly one, correctly formatted record.",
    riskRating: "moderate",
    priority: "now",
    effort: "low",
    status: "attention",
  },
  DMARC_STRONG: {
    controlId: "DMARC_STRONG",
    concept: "dmarc",
    title: "DMARC is configured with an enforcement policy",
    why: "Your domain publishes a DMARC policy that instructs receiving mail systems to reject or quarantine messages that fail authentication.",
    recommendation: "No action needed. Continue reviewing DMARC aggregate reports periodically if you receive them.",
    riskRating: "informational",
    priority: "monitor",
    effort: "very-low",
    status: "good",
  },

  DKIM_NOT_CONFIRMED: {
    controlId: "DKIM_NOT_CONFIRMED",
    concept: "dkim",
    title: "DKIM could not be externally confirmed",
    why: "DKIM selectors generally cannot be discovered from outside without already knowing them. This does not mean DKIM is missing, only that it could not be verified from public information alone.",
    recommendation: "Confirm DKIM is configured directly with your mail provider or IT provider, since this is often set up by default but is worth verifying explicitly.",
    riskRating: "low",
    priority: "next",
    effort: "low",
    status: "attention",
  },
  DKIM_MISCONFIGURED: {
    controlId: "DKIM_MISCONFIGURED",
    concept: "dkim",
    title: "A DKIM record was found but does not look correctly configured",
    why: "A DNS record exists at the expected location for DKIM, but does not contain the fields a valid DKIM key record needs.",
    recommendation: "Review DKIM configuration with your mail provider or IT provider.",
    riskRating: "moderate",
    priority: "next",
    effort: "moderate",
    status: "attention",
  },
  DKIM_CONFIRMED: {
    controlId: "DKIM_CONFIRMED",
    concept: "dkim",
    title: "DKIM was confirmed configured",
    why: "A valid DKIM key record was found for a selector documented as a default for your mail provider.",
    recommendation: "No action needed.",
    riskRating: "informational",
    priority: "monitor",
    effort: "very-low",
    status: "good",
  },

  DNSSEC_NOT_VALIDATED: {
    controlId: "DNSSEC_NOT_VALIDATED",
    concept: "dnssec",
    title: "DNSSEC does not appear to be validated for this domain",
    why: "DNSSEC helps protect against certain DNS manipulation attacks by allowing DNS responses to be cryptographically verified. Most small businesses do not have this configured, and it is a lower-priority item than email authentication or backups.",
    recommendation: "Worth considering once higher-priority items are addressed. Ask your DNS/domain provider whether they support DNSSEC signing.",
    riskRating: "low",
    priority: "later",
    effort: "moderate",
    status: "attention",
  },
  DNSSEC_VALIDATED: {
    controlId: "DNSSEC_VALIDATED",
    concept: "dnssec",
    title: "DNSSEC is validated for this domain",
    why: "A validating DNS resolver confirmed this domain's DNS responses can be cryptographically verified.",
    recommendation: "No action needed.",
    riskRating: "informational",
    priority: "monitor",
    effort: "very-low",
    status: "good",
  },

  REGISTRATION_EXPIRING_SOON: {
    controlId: "REGISTRATION_EXPIRING_SOON",
    concept: "domain-registration",
    title: "Domain registration expires soon",
    why: "If a domain registration lapses, the business can lose control of its website and email entirely, sometimes to whoever registers it next.",
    recommendation: "Confirm the domain is set to auto-renew with your registrar, and that billing details are current.",
    riskRating: "moderate",
    priority: "now",
    effort: "very-low",
    status: "attention",
  },
  REGISTRATION_NOT_AVAILABLE: {
    controlId: "REGISTRATION_NOT_AVAILABLE",
    concept: "domain-registration",
    title: "Domain registration details were not available",
    why: "Registration information could not be retrieved from the registry for this domain during this scan.",
    recommendation: "No action implied by this alone. If you'd like this confirmed, ask your domain registrar directly.",
    riskRating: "informational",
    priority: "monitor",
    effort: "very-low",
    status: "not-checked",
  },

  SUBDOMAIN_NONPRODUCTION_EXPOSED: {
    controlId: "SUBDOMAIN_NONPRODUCTION_EXPOSED",
    concept: "public-footprint",
    title: "A hostname suggesting a development or staging environment is currently resolving",
    why: "Development, staging, and legacy environments can sometimes receive less security attention than production services, while still being reachable from the internet.",
    recommendation: "Confirm whether this host is still required. If so, ensure it receives the same security attention as production; if not, consider retiring it.",
    riskRating: "moderate",
    priority: "next",
    effort: "low",
    status: "attention",
  },

  SUBDOMAIN_TAKEOVER_RISK: {
    controlId: "SUBDOMAIN_TAKEOVER_RISK",
    concept: "subdomain-takeover",
    title: "A subdomain may be vulnerable to takeover",
    why: "This subdomain points to a third-party service that doesn't appear to be claimed any more. If so, someone else could potentially claim that same service address and serve their own content, including a convincing phishing page, from a subdomain of your own domain.",
    recommendation: "Confirm whether this subdomain and the service it points to are still in use. If not, remove the DNS record; if it should still be active, reclaim or reconfigure the service it points to.",
    riskRating: "high",
    priority: "now",
    effort: "low",
    status: "high-priority",
  },

  CAA_MISSING: {
    controlId: "CAA_MISSING",
    concept: "caa",
    title: "No CAA record was found",
    why: "Without a CAA record, any publicly trusted certificate authority can issue an SSL/TLS certificate for your domain. This has been standard, workable practice on the web for years and isn't a pressing risk on its own.",
    recommendation: "A low-effort, lower-priority improvement: add a CAA record naming the certificate authority (or authorities) you actually use.",
    riskRating: "low",
    priority: "later",
    effort: "very-low",
    status: "attention",
  },
  CAA_PRESENT: {
    controlId: "CAA_PRESENT",
    concept: "caa",
    title: "A CAA record restricts which certificate authorities can issue for this domain",
    why: "Your domain publishes a CAA record narrowing which certificate authorities are allowed to issue certificates for it.",
    recommendation: "No action needed.",
    riskRating: "informational",
    priority: "monitor",
    effort: "very-low",
    status: "good",
  },

  CERTIFICATE_CURRENT: {
    controlId: "CERTIFICATE_CURRENT",
    concept: "tls-certificate",
    title: "A recently issued certificate was found for your primary site",
    why: "Public certificate transparency logs show a certificate issued for your main website within the timeframe expected for typical automatic renewal.",
    recommendation: "No action needed.",
    riskRating: "informational",
    priority: "monitor",
    effort: "very-low",
    status: "good",
  },
  CERTIFICATE_STALE_OR_EXPIRED: {
    controlId: "CERTIFICATE_STALE_OR_EXPIRED",
    concept: "tls-certificate",
    title: "The most recently logged certificate for your primary site has expired",
    why: "Public certificate transparency logs show the most recent certificate for your main website is past its expiry date. This may already have been renewed, since certificate transparency data can lag behind what's actually live, but is worth confirming.",
    recommendation: "Confirm your website is currently serving a valid, unexpired certificate, and that renewal happens automatically going forward.",
    riskRating: "moderate",
    priority: "now",
    effort: "very-low",
    status: "attention",
  },
  CERTIFICATE_NOT_FOUND: {
    controlId: "CERTIFICATE_NOT_FOUND",
    concept: "tls-certificate",
    title: "No certificate history was found for your primary site",
    why: "No certificate covering your main domain or its www address appears in public certificate transparency logs. This can mean the site doesn't serve HTTPS, or simply that it uses a certificate type or provider with limited log visibility.",
    recommendation: "Confirm your main website is served over HTTPS with a valid, trusted certificate.",
    riskRating: "low",
    priority: "next",
    effort: "very-low",
    status: "attention",
  },

  MTA_STS_MISSING: {
    controlId: "MTA_STS_MISSING",
    concept: "mta-sts",
    title: "MTA-STS was not found",
    why: "MTA-STS tells other mail servers to always deliver to your domain over an encrypted, verified connection. It's a newer standard, not yet as widely adopted as SPF, DMARC, and DKIM, and is a reasonable next step after those are solid.",
    recommendation: "Worth considering once your core email authentication (SPF, DKIM, DMARC) is confirmed solid. Ask your mail provider whether they support it.",
    riskRating: "low",
    priority: "later",
    effort: "moderate",
    status: "attention",
  },
  MTA_STS_PRESENT: {
    controlId: "MTA_STS_PRESENT",
    concept: "mta-sts",
    title: "MTA-STS is configured",
    why: "Your domain publishes an MTA-STS policy, so other mail servers know to always deliver to you over an encrypted, verified connection.",
    recommendation: "No action needed.",
    riskRating: "informational",
    priority: "monitor",
    effort: "very-low",
    status: "good",
  },

  BIMI_PRESENT: {
    controlId: "BIMI_PRESENT",
    concept: "bimi",
    title: "BIMI is configured",
    why: "Your domain publishes a BIMI record, which can display your verified logo next to your emails in supporting inboxes. This only works alongside a strong DMARC policy, so it's a visible sign that email authentication is properly set up.",
    recommendation: "No action needed.",
    riskRating: "informational",
    priority: "monitor",
    effort: "very-low",
    status: "good",
  },

  INTERNET_EXPOSURE_CRITICAL: {
    controlId: "INTERNET_EXPOSURE_CRITICAL",
    concept: "internet-exposure",
    title: "A commonly-exploited remote access service has previously been observed",
    why: "Remote desktop (RDP) and Telnet are two of the most common entry points used in ransomware and other mass-exploitation attacks when left directly reachable from the internet without other protections.",
    recommendation: "Confirm whether this is intentional. If remote access is needed, it should sit behind a VPN or similarly protected connection rather than being directly reachable from the internet. If it's not needed, disable it.",
    riskRating: "high",
    priority: "now",
    effort: "moderate",
    status: "high-priority",
  },
  INTERNET_EXPOSURE_SENSITIVE: {
    controlId: "INTERNET_EXPOSURE_SENSITIVE",
    concept: "internet-exposure",
    title: "Administrative or database services have previously been observed",
    why: "These are the kinds of services usually meant for internal or administrative use, not the general public. Their presence alone isn't proof of a weakness, since they may be properly secured, but they're worth confirming.",
    recommendation: "Confirm these services are intentionally reachable from the internet and are properly secured (strong authentication, kept up to date, and restricted to only those who need access).",
    riskRating: "moderate",
    priority: "next",
    effort: "moderate",
    status: "attention",
  },
  INTERNET_EXPOSURE_ROUTINE: {
    controlId: "INTERNET_EXPOSURE_ROUTINE",
    concept: "internet-exposure",
    title: "Only routine web services have previously been observed",
    why: "Previously-observed services associated with this domain's IP address are limited to standard web traffic, nothing that stands out as unusual.",
    recommendation: "No action needed.",
    riskRating: "informational",
    priority: "monitor",
    effort: "very-low",
    status: "good",
  },
  INTERNET_EXPOSURE_NOT_CHECKED: {
    controlId: "INTERNET_EXPOSURE_NOT_CHECKED",
    concept: "internet-exposure",
    title: "Previously-observed internet services were not checked",
    why: "This check uses a paid internet-scanning intelligence provider that isn't configured for this scan.",
    recommendation: "No action implied by this alone.",
    riskRating: "informational",
    priority: "monitor",
    effort: "very-low",
    status: "not-checked",
  },
};

export function getKnowledgeBaseEntry(controlId: string): KnowledgeBaseEntry {
  const entry = KNOWLEDGE_BASE[controlId];
  if (!entry) {
    throw new Error(`Unknown remediation knowledge base control ID: ${controlId}`);
  }
  return entry;
}
